"""
Configuración central del proyecto de predicción de enfermedades y triaje.
"""
import os

# ============================================================
# RUTAS
# ============================================================
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INSUMOS_DIR = os.path.join(BASE_DIR, "insumos")
MODELS_DIR = os.path.join(BASE_DIR, "models")
OUTPUTS_DIR = os.path.join(BASE_DIR, "outputs")

# Archivos de entrada
ENFERMEDAD_XLSX = os.path.join(INSUMOS_DIR, "sintomas_vs_enfermedades.xlsx")
MORBILIDAD_XLSX = os.path.join(INSUMOS_DIR, "Morbilidad_urgencias_Hospital_Pitalito_20260406.xlsx")

# ============================================================
# CONSTANTES DEL MODELO
# ============================================================
RANDOM_STATE = 42
TEST_SIZE = 0.2
CV_FOLDS = 5

# Niveles de triaje a excluir (muy pocas muestras: 0=1 caso, 5=23 casos)
TRIAJE_EXCLUIDO = [0, 5]
TRIAJE_LABELS = {1: "Resucitación", 2: "Emergencia", 3: "Urgencia", 4: "Menos urgente"}

# ============================================================
# DICCIONARIO DE MAPEO: DxSindromatico → Síntomas en español
# ============================================================
# Mapeo de los diagnósticos sindrómicos del hospital
# a los nombres de columnas del dataset sintomas_vs_enfermedades.xlsx
SINDROMATICO_A_SINTOMAS = {
    "ABDOMEN AGUDO": ['abdomen hinchado', 'dolor abdominal agudo', 'dolor en la parte baja del abdomen', 'dolor en la parte superior del abdomen', 'dolor agudo en el pecho', 'náuseas', 'vómitos'],
    "ABORTO RETENIDO": ['sangrado intermenstrual', 'dolor abdominal agudo', 'sangrado vaginal después de la menopausia'],
    "ABSCESO PERIMIGDALINOS": ['enrojecimiento del pene', 'pus en el esputo', 'fiebre', 'hinchazón de la piel'],
    "ABSCESO PIEL": ['dolor de piel', 'lunares en la piel', 'hinchazón de la piel', 'irritación de la piel', 'picazón en la piel', 'piel grasa', 'crecimiento de la piel', 'arrugas en la piel', 'enrojecimiento del pene', 'pus en el esputo'],
    "ABUSO FISICO": ['abuso de alcohol', 'abuso de drogas', 'visión disminuida', 'manchas o nubes en la visión', 'dolor muscular', 'dolor pélvico', 'síntomas emocionales'],
    "ABUSO SEXUAL": ['abuso de alcohol', 'abuso de drogas', 'pérdida del deseo sexual', 'dolor muscular', 'dolor pélvico', 'síntomas emocionales'],
    "ACCIDENTE  CEREBRO VASCULAR": ['debilidad', 'dificultad para hablar', 'dolor de cabeza'],
    "ACCIDENTE DE TRANSITO": ['debilidad', 'dificultad para hablar', 'dolor de cabeza', 'sangrado vaginal después de la menopausia', 'dolor abdominal agudo', 'síntomas depresivos o psicóticos', 'síntomas emocionales', 'insomnio', 'sangrado intermenstrual'],
    "ACCIDENTE EN DOMICILIO": ['debilidad', 'dificultad para hablar', 'dolor de cabeza', 'síntomas emocionales', 'depresión', 'sangrado intermenstrual'],
    "ACCIDENTE LABORAL": ['debilidad', 'dificultad para hablar', 'dolor de cabeza', 'sangrado intermenstrual'],
    "ALERGIA NO ESPECIFICADA": ['sangrado intermenstrual', 'dolor agudo en el pecho', 'opresión en el pecho', 'palpitaciones', 'debilidad', 'mareo', 'dolor de cabeza', 'náuseas', 'movimientos involuntarios anormales', 'dificultad para hablar'],
    "ALERGIA, CONGESTION NASAL, ESTORNUDOS": ['congestión nasal', 'congestión sinusal', 'congestión en el pecho', 'hemorragia nasal', 'deformidad nasal'],
    "ALTERACION VISUAL NO ESPECIFICADA": ['alteración de la memoria', 'alteración del olfato o del gusto', 'secreción peneana'],
    "AMENAZA DE PARTO PRETERMINO": ['dolor abdominal agudo', 'síntomas depresivos o psicóticos', 'síntomas emocionales'],
    "AMENORREA SIN OTRA ESPECIFICACION": ['dificultad para respirar', 'diarrea', 'náuseas', 'dolor abdominal agudo', 'congestión nasal', 'tos', 'dolor de garganta', 'dolor pélvico', 'flujo menstrual escaso', 'sangrado intermenstrual'],
    "AMENORREA SIN SANGRADO O DOLOR": ['sangrado del oído', 'sangrado del ojo', 'sangrado de lengua', 'sangrado rectal', 'sangrado intermenstrual', 'sangrado en la boca', 'sangrado o secreción del pezón', 'sangrado o manchado durante el embarazo', 'sangre en las heces'],
    "AMIGDALITIS AGUDA": ['dolor de garganta', 'fiebre', 'dificultad para tragar'],
    "AMPUTACION TRAUMATICA": ['sangrado intermenstrual', 'problema de alimentación infantil', 'dificultad para respirar'],
    "ANEMIA NUTRICIONAL": ['sangrado intermenstrual', 'dificultad para respirar', 'palpitaciones', 'masa en la ingle', 'dolor abdominal agudo', 'retención de líquidos', 'ictericia', 'falta de crecimiento', 'fatiga', 'palidez'],
    "ANEMIA POR DEFICIENCIA DE HIERRO": ['dificultad para respirar', 'palpitaciones'],
    "ANEMIA POR DEFICIENCIA DE HIERRO SIN OTRA ESPECIFICACION": ['dificultad para respirar', 'palpitaciones'],
    "ANEURISMA  ABDOMINAL": ['distensión abdominal', 'dolor abdominal ardiente', 'dolor abdominal agudo', 'náuseas', 'vómitos', 'dolor de espalda'],
    "ANGINA INESTABLE": ['dolor agudo en el pecho', 'opresión en el pecho', 'palpitaciones', 'sangrado vaginal después de la menopausia', 'sangrado intermenstrual', 'dolor pélvico'],
    "APENDICITIS AGUDA": ['dolor abdominal agudo', 'náuseas', 'fiebre', 'vómitos', 'dolor de garganta', 'dificultad para tragar'],
    "APNEA": ['apnea', 'dificultad para respirar', 'flujo menstrual escaso', 'sangrado intermenstrual', 'fatiga', 'palidez', 'mareo', 'debilidad', 'ansiedad y nerviosismo', 'palpitaciones'],
    "ARDOR OCULAR": ['fatiga ocular', 'desviación ocular', 'lagrimeo', 'dolor muscular'],
    "ARDOR PARA ORINAR": ['sangrado vaginal después de la menopausia', 'sangrado intermenstrual', 'dolor pélvico', 'dificultad para respirar', 'problema de alimentación infantil', 'ictericia', 'lagrimeo'],
    "ARTRALGIAS": ['sangrado intermenstrual', 'debilidad', 'mareo', 'dolor agudo en el pecho', 'problemas mamarios posparto', 'reacción alérgica', 'picazón en la piel', 'erupción cutánea', 'congestión nasal', 'verrugas'],
    "ARTRALGIAS  FIEBRE": ['fiebre', 'dolor articular', 'hinchazón de las articulaciones'],
    "AUSENCIA PULSO  PARO": ['ausencia de menstruación', 'dolor abdominal agudo'],
    "BARTHOLINITIS": ['zumbido en el oído', 'audición disminuida', 'dolor abdominal agudo', 'náuseas', 'vómitos', 'fiebre', 'diarrea', 'tos', 'dificultad para respirar', 'flujo vaginal'],
    "BLEFAROCONJUNTIVITIS": ['tos', 'dificultad para respirar', 'fiebre', 'lagrimeo', 'secreción blanca del ojo', 'El ojo se mueve de forma anormal.'],
    "BLOQUEO AURICULAR - VENTRICULAR": ['arritmia', 'palpitaciones', 'mareo'],
    "BRADICARDIA": ['palpitaciones', 'arritmia', 'respirando rápido', 'mareo', 'dificultad para respirar', 'diarrea', 'náuseas', 'dolor abdominal agudo', 'dolor suprapúbico', 'reacción alérgica'],
    "BRONQUIOLITIS": ['tos', 'dificultad para respirar', 'fiebre', 'dolor vaginal', 'lagrimeo', 'secreción blanca del ojo', 'El ojo se mueve de forma anormal.'],
    "CAMBIOS GRADUALES DE VISION NO SUBITOS": ['visión disminuida', 'visión doble', 'manchas o nubes en la visión', 'cambios en la apariencia de las heces'],
    "CEFALEA": ['cefalea frontal', 'dolor de cabeza', 'mareo', 'náuseas', 'reacción alérgica', 'picazón en la piel', 'erupción cutánea', 'congestión nasal'],
    "CEFALEA CRONICA": ['cefalea frontal', 'dolor de cabeza', 'mareo', 'náuseas'],
    "CEFALEA INTENSA MIGRAÑA": ['cefalea frontal'],
    "CEFALEA Y FIEBRE": ['fiebre', 'cefalea frontal', 'dolor de cabeza', 'mareo', 'náuseas'],
    "CELULITIS DE SITIO NO ESPECIFICADO": ['hemorragia nasal', 'sangrado en la boca', 'dolor abdominal agudo', 'náuseas', 'vómitos', 'fiebre', 'ictericia', 'fatiga', 'enrojecimiento del pene', 'hinchazón de la piel'],
    "CIANOSIS": ['dificultad para respirar', 'respirando rápido', 'vomitar sangre', 'náuseas', 'dolor pélvico', 'flujo menstrual abundante', 'dolor abdominal agudo', 'picazón en la piel', 'erupción cutánea'],
    "COLECISTITIS": ['hemorragia nasal', 'sangrado en la boca', 'dolor abdominal agudo', 'náuseas', 'vómitos', 'fiebre', 'ictericia', 'fatiga', 'dolor vaginal', 'problemas mamarios posparto'],
    "COLICO MENSTRUAL": ['flujo menstrual escaso', 'flujo menstrual abundante', 'dolor abdominal agudo'],
    "CONJUNTIVITIS": ['dolor abdominal agudo', 'náuseas', 'vómitos', 'tos', 'dificultad para respirar', 'fiebre', 'lagrimeo', 'secreción blanca del ojo', 'El ojo se mueve de forma anormal.'],
    "CONJUNTIVITIS AGUDA NO ESPECIFICADA": ['lagrimeo', 'secreción blanca del ojo', 'El ojo se mueve de forma anormal.', 'sangrado del ojo'],
    "CONJUNTIVITIS VIRAL SIN OTRA ESPECIFICACION": ['lagrimeo', 'secreción blanca del ojo', 'El ojo se mueve de forma anormal.'],
    "CONTUSIONES": ['dolor muscular', 'convulsiones', 'movimientos involuntarios anormales', 'retención de orina'],
    "CRISIS  ASMATICAS": ['dificultad para respirar', 'opresión en el pecho', 'tos'],
    "CUERPO EXTRAÑO EN EL OJO": ['Sensación de cuerpo extraño en el ojo', 'dolor en la parte inferior del cuerpo', 'dolor en el ojo', 'ojo hinchado', 'sangrado del ojo', 'picazón en el ojo', 'síntomas del ojo', 'lagrimeo', 'congestión nasal', 'hemorragia nasal'],
    "CUERPO EXTRAÑO EN FARINGE ASOCIADO A DISNEA": ['Sensación de cuerpo extraño en el ojo', 'dolor en la parte inferior del cuerpo', 'congestión nasal', 'hemorragia nasal', 'pus que drena del oído', 'audición disminuida', 'dificultad para tragar', 'dolor de garganta'],
    "CUERPO EXTRAÑO EN FARINGE SIN DISNEA": ['Sensación de cuerpo extraño en el ojo', 'dolor en la parte inferior del cuerpo', 'dolor en el ojo', 'lagrimeo', 'congestión nasal', 'hemorragia nasal', 'pus que drena del oído', 'audición disminuida', 'dificultad para tragar', 'dolor de garganta'],
    "CUERPO EXTRAÑO EN NARIZ": ['Sensación de cuerpo extraño en el ojo', 'dolor en la nariz', 'dolor en la parte inferior del cuerpo', 'enrojecimiento en o alrededor de la nariz', 'dolor en el ojo', 'lagrimeo', 'congestión nasal', 'hemorragia nasal', 'pus que drena del oído', 'audición disminuida'],
    "CUERPO EXTRAÑO EN OIDO": ['Sensación de cuerpo extraño en el ojo', 'enrojecimiento en el oído', 'dolor en la parte inferior del cuerpo', 'dolor de oído', 'líquido en el oído', 'sangrado del oído', 'zumbido en el oído', 'picazón en el oído(s)', 'dolor en el ojo', 'lagrimeo'],
    "CUERPO EXTRAÑO EN PARTE EXTERNA DEL OJO": ['Sensación de cuerpo extraño en el ojo', 'dolor en la parte inferior del cuerpo', 'dolor en el ojo', 'ojo hinchado', 'ojo nublado', 'sangrado del ojo', 'síntomas del ojo', 'picazón en el ojo', 'lagrimeo', 'congestión nasal'],
    "CUERPO EXTRAÑO QUE PENETRA POR EL OJO U ORIFICIO NATURAL": ['Sensación de cuerpo extraño en el ojo', 'dolor en la parte inferior del cuerpo', 'dolor en el ojo', 'picazón en el ojo', 'síntomas del ojo', 'sangrado del ojo', 'ojo hinchado', 'ojo nublado', 'lagrimeo', 'congestión nasal'],
    "CUERPO EXTRAÑO URETRAL": ['Sensación de cuerpo extraño en el ojo', 'dolor en la parte inferior del cuerpo', 'secreción peneana', 'dolor en el ojo', 'lagrimeo', 'congestión nasal', 'hemorragia nasal', 'pus que drena del oído', 'audición disminuida', 'dificultad para tragar'],
    "DEFORMIDAD EN ARTICULACION CON DOLOR": ['deformidad nasal', 'dolor de cadera', 'dolor de codo', 'dolor de cuello', 'dolor de ano', 'dolor en el brazo', 'dolor de oído', 'dolor de tobillo'],
    "DEMENCIA NO ESPECIFICADA": ['síntomas emocionales', 'vómitos', 'náuseas', 'retención de líquidos', 'fatiga', 'palidez', 'mareo', 'debilidad', 'dolor muscular'],
    "DERMATITIS ALERGICA DE CONTACTO DE CAUSA NO ESPECIFICADA": ['reacción alérgica', 'dermatitis del pañal'],
    "DERMATITIS ATOPICA NO ESPECIFICADA": ['dermatitis del pañal', 'dificultad para respirar', 'opresión en el pecho', 'tos', 'dolor abdominal agudo', 'náuseas', 'fiebre', 'vómitos', 'dolor de garganta', 'dificultad para tragar'],
    "DERMATITIS DE CONTACTO, FORMA Y CAUSA NO ESPECIFICADAS": ['dermatitis del pañal'],
    "DERMATITIS HERPETIFORME": ['dermatitis del pañal', 'picazón en la piel', 'erupción cutánea', 'enrojecimiento del pene'],
    "DERMATITIS INFECCIOSA": ['dermatitis del pañal', 'picazón en la piel', 'erupción cutánea', 'enrojecimiento del pene', 'secreción peneana', 'lesiones en la lengua'],
    "DERMATITIS NO ESPECIFICADA": ['dermatitis del pañal', 'vomitar sangre', 'náuseas', 'vómitos', 'pus en el esputo', 'tos', 'dificultad para respirar', 'dolor abdominal agudo', 'fiebre', 'ictericia'],
    "DERMATITIS SEBORREICA NO ESPECIFICADA": ['dermatitis del pañal', 'dolor pélvico', 'dolor abdominal agudo', 'picazón en la piel', 'erupción cutánea', 'enrojecimiento del pene'],
    "DETERIORO ESTADO CONSCIENCIA": ['dificultad para respirar', 'respirando rápido'],
    "DIABETES": ['poliuria', 'fatiga', 'hinchazón del pie o del dedo del pie', 'dolor en el pie o en los dedos del pie', 'La piel de la pierna o el pie parece infectada.'],
    "DIARREA GASTROENTERITIS PRESUNTO ORIGEN INFECCIOSO": ['diarrea'],
    "DIARREA SIN COMPROMISO GENERAL": ['diarrea'],
    "DICTAMEN DE EMBRIAGUEZ": ['mareo'],
    "DIPLOPIA": ['desmayo', 'mareo', 'debilidad', 'movimientos involuntarios anormales', 'dolor de garganta', 'dificultad para tragar', 'fiebre', 'voz ronca', 'dificultad para hablar', 'visión doble'],
    "DISFONIA": ['dificultad para respirar', 'opresión en el pecho', 'respirando rápido', 'dolor de garganta', 'dificultad para tragar', 'fiebre', 'voz ronca', 'dificultad para hablar', 'dolor suprapúbico', 'visión doble'],
    "DISMENORREA": ['dificultad para respirar', 'opresión en el pecho', 'respirando rápido', 'diarrea', 'náuseas', 'dolor abdominal agudo', 'congestión nasal', 'tos', 'dolor de garganta', 'dolor suprapúbico'],
    "DISMINUCION EN LOS MOVIMIENTOS FETALES": ['disminución del apetito', 'movimientos involuntarios anormales', 'disminución de la frecuencia cardíaca', 'dolor abdominal agudo'],
    "DISMINUCION SUBITA AGUDEZA VISUAL": ['disminución del apetito', 'disminución de la frecuencia cardíaca', 'dolor abdominal agudo'],
    "DISNEA MODERADA": ['dificultad para respirar', 'opresión en el pecho', 'respirando rápido'],
    "DISNEA PACIENTE CON EPOC": ['sangrado intermenstrual'],
    "DISNEA SUBITA": ['dificultad para respirar', 'opresión en el pecho', 'respirando rápido', 'voz ronca', 'dificultad para hablar', 'dolor suprapúbico'],
    "DISURIA POLAQUIURIA SIN FIEBRE VOMITO": ['fiebre'],
    "DISURIA, POLAQUIURIA, FIEBRE": ['fiebre', 'dolor suprapúbico'],
    "DOLOR ABDOMINAL": ['dolor abdominal agudo', 'dolor abdominal ardiente', 'distensión abdominal', 'dolor de cadera', 'dolor de ano', 'dolor de codo', 'dolor en el brazo', 'náuseas', 'vómitos'],
    "DOLOR ABDOMINAL  FIEBRE  FLUJO VAGINAL": ['flujo vaginal', 'dolor abdominal ardiente', 'dolor abdominal agudo', 'fiebre', 'dolor vaginal', 'distensión abdominal', 'enrojecimiento vaginal', 'picazón vaginal', 'náuseas'],
    "DOLOR ABDOMINAL CON DIARREA Y DHT": ['dolor abdominal ardiente', 'dolor abdominal agudo', 'diarrea', 'distensión abdominal', 'náuseas'],
    "DOLOR ABDOMINAL CONSTANTE": ['dolor abdominal ardiente', 'dolor abdominal agudo', 'distensión abdominal', 'náuseas'],
    "DOLOR ABDOMINAL EN MUJER SEXUALMENTE ACTIVA": ['dolor abdominal ardiente', 'dolor abdominal agudo', 'distensión abdominal', 'náuseas'],
    "DOLOR ABDOMINAL INTERMITENTE": ['dolor abdominal ardiente', 'dolor abdominal agudo', 'distensión abdominal', 'náuseas'],
    "DOLOR ABDOMINAL POSTQUIRURGICO": ['dolor abdominal agudo', 'dolor abdominal ardiente', 'distensión abdominal', 'náuseas'],
    "DOLOR ABDOMINAL SEVERO": ['dolor abdominal agudo', 'dolor abdominal ardiente', 'distensión abdominal', 'náuseas'],
    "DOLOR AGUDO": ['dolor agudo en el pecho', 'dolor abdominal agudo', 'dolor de ano', 'dolor de codo', 'dolor en el brazo', 'dolor de cuello', 'dolor de cadera', 'náuseas', 'lagrimeo'],
    "DOLOR ARTICULAR EN PACIENTE HEMOFILICO": ['dolor articular'],
    "DOLOR CRONICO": ['dolor de codo', 'dolor de ano', 'dolor en el brazo', 'dolor de cuello', 'dolor de cadera', 'dolor de cabeza', 'dolor de piel', 'dolor en el ojo'],
    "DOLOR DE ESPALDA": ['dolor de espalda', 'debilidad en la espalda', 'hinchazón de espalda', 'bulto o masa en la espalda', 'dolor de piel', 'debilidad en la parte baja de la espalda', 'calambres o espasmos en la espalda', 'dolor de encías', 'dolor abdominal agudo'],
    "DOLOR EN DORSO LOCALIZADO": ['dolor de oído', 'dolor de rodilla', 'dolor de espalda', 'dolor de tobillo', 'dolor muscular', 'dolor en el ojo', 'dolor en las encías', 'dolor de encías'],
    "DOLOR LUMBAR CRONICO": ['dolor de codo', 'dolor de lengua', 'dolor de hombro', 'dolor de ano', 'dolor en el brazo', 'dolor de espalda', 'dolor muscular', 'dolor de piel'],
    "DOLOR LUMBAR IRRADIADO Y PARESTESIAS": ['dolor de garganta', 'dolor de rodilla', 'dolor en las encías', 'dolor de encías', 'dolor de hombro', 'dolor vaginal', 'dolor de oído', 'dolor de mandíbula'],
    "DOLOR LUMBAR SIN SINTOMAS ASOCIADOS": ['síntomas del ojo', 'síntomas de la cara', 'síntomas emocionales', 'síntomas de los riñones', 'síntomas de próstata', 'síntomas de los bebés', 'síntomas de vejiga', 'síntomas depresivos o psicóticos'],
    "DOLOR MUSCULAR SIN OTROS SINTOMAS": ['dolor muscular', 'debilidad muscular', 'hinchazón muscular', 'síntomas del ojo', 'síntomas de la cara', 'síntomas de próstata', 'síntomas de los riñones', 'síntomas emocionales', 'sangrado del ojo', 'dolor en el ojo'],
    "DOLOR NO ESPECIFICADO": ['dolor en el ojo', 'dolor de piel', 'dolor de ano', 'dolor de oído', 'dolor de codo', 'dolor de pene', 'dolor en el brazo', 'dolor de cuello'],
    "DOLOR OCULAR": ['desviación ocular', 'fatiga ocular', 'dolor muscular', 'dolor de rodilla', 'dolor en el ojo', 'dolor en las encías', 'dolor de encías', 'dolor de lengua', 'lagrimeo'],
    "DOLOR PRECORDIAL": ['dolor de rodilla', 'dolor de piel', 'dolor en las encías', 'dolor de encías', 'dolor en la pierna', 'dolor de espalda', 'dolor de muñeca', 'dolor de oído'],
    "DOLOR PUNZANTE  CEFALEA": ['cefalea frontal', 'dolor de cadera', 'dolor de pene', 'dolor de cuello', 'dolor de muñeca', 'dolor de piel', 'dolor en la pierna', 'dolor de garganta'],
    "DOLOR SEVERO EN EXTREMIDAD CON COMPROMISO CIRCULATORIO": ['dolor de cuello', 'dolor en las encías', 'dolor de encías', 'dolor de oído', 'dolor de espalda', 'dolor de piel', 'dolor de codo', 'dolor en el brazo'],
    "DOLOR SEVERO EN MAMAS  FIEBRE": ['fiebre', 'dolor en la pierna', 'dolor de espalda', 'dolor en las encías', 'dolor de encías', 'dolor de hombro', 'dolor de piel', 'dolor de garganta'],
    "DOLOR SEVERO TIPO COLICO EN FLANCO + HEMATURIA": ['dolor en las encías', 'dolor de encías', 'dolor de lengua', 'dolor de hombro', 'dolor de garganta', 'dolor de oído', 'dolor de espalda', 'dolor de codo'],
    "DOLOR TORACICO CON LA INSPIRACION": ['dolor de garganta', 'dolor en la pierna', 'dolor de espalda', 'dolor en las encías', 'dolor de encías', 'dolor de oído', 'dolor vaginal', 'dolor de tobillo'],
    "DOLOR TORACICO CON LA PALPACION": ['dolor de garganta', 'dolor de espalda', 'dolor de oído', 'dolor vaginal', 'dolor en la pierna', 'dolor de tobillo', 'dolor de piel', 'dolor en el ojo'],
    "DOLOR TORACICO CON LOS MOVIMIENTOS DEL TRONCO": ['movimientos involuntarios anormales', 'dolor de encías', 'dolor en las encías', 'dolor de hombro', 'dolor vaginal', 'dolor en la pierna', 'dolor de tobillo', 'dolor de oído'],
    "DOLOR TORACICO CON TOS Y FIEBRE": ['fiebre', 'tos'],
    "DOLOR TORACICO IRRADIADO A CUELLO BRAZO CO DISNEA NAUSEAS O DIAFORESIS": ['náuseas', 'dolor en el brazo', 'dolor de cuello', 'debilidad en el brazo', 'debilidad en el cuello', 'hinchazón del brazo', 'hinchazón del cuello', 'masa en el cuello'],
    "DOLOR TORAXICO": ['dolor de oído', 'dolor de tobillo', 'dolor en el ojo', 'dolor de hombro', 'dolor de piel', 'dolor vaginal', 'dolor de rodilla', 'dolor en la pierna'],
    "EDEMA GESTACIONAL": ['edema periférico', 'síntomas emocionales', 'retención de líquidos'],
    "EDEMA SIN TRAUMA": ['edema periférico', 'dolor muscular', 'dolor de espalda', 'sangre en la orina', 'retención de líquidos', 'síntomas del ojo', 'sangrado del ojo', 'dolor en el ojo'],
    "EMESIS CUNCHO CAFE": ['vomitar sangre', 'náuseas'],
    "ENDOMETRIOSIS": ['pus en el esputo', 'tos', 'dificultad para respirar', 'vómitos', 'náuseas', 'dolor pélvico', 'sangrado intermenstrual', 'flujo menstrual abundante', 'dolor abdominal agudo', 'dolor de rodilla'],
    "ENFERMEDAD DE TRANSMISION SEXUAL": ['pérdida del deseo sexual', 'dificultad para respirar', 'tos', 'pus en el esputo', 'dolor pélvico', 'fiebre', 'flujo vaginal'],
    "ENFERMEDAD PELVICA INFLAMATORIA": ['presión pélvica', 'dificultad para respirar', 'tos', 'pus en el esputo', 'dolor pélvico', 'fiebre', 'flujo vaginal'],
    "ENFERMEDAD PULMONAR": ['dificultad para respirar', 'tos', 'pus en el esputo', 'dolor pélvico', 'fiebre', 'flujo vaginal'],
    "ENVENENAMIENTO ACCIDENTAL": ['sangrado vaginal después de la menopausia', 'dolor abdominal agudo', 'náuseas', 'vómitos'],
    "EPISODIO CONVULSION": ['dolor muscular', 'convulsiones', 'movimientos involuntarios anormales', 'depresión', 'insomnio', 'síntomas emocionales'],
    "EPISODIO DE PARESIA O PLEJIA": ['debilidad', 'movimientos involuntarios anormales'],
    "EPISODIO DEPRESIVO": ['depresión', 'insomnio', 'síntomas emocionales'],
    "EPISTAXIS + HTA + CEFALEA": ['cefalea frontal', 'dificultad para respirar', 'respirando rápido', 'hemorragia nasal', 'sangrado en la boca'],
    "ESGUINCE": ['dolor articular', 'hinchazón de las articulaciones', 'desmayo', 'mareo', 'debilidad'],
    "ESPASMO MUSCULAR": ['dolor muscular', 'hinchazón muscular', 'debilidad muscular', 'rigidez o tensión muscular', 'lagrimeo'],
    "ESQUIZOFRENIA CON SINTOMAS DE ALUCINACIONES": ['delirios o alucinaciones', 'síntomas de los riñones', 'síntomas emocionales', 'síntomas de la cara', 'síntomas del ojo', 'síntomas de los bebés', 'síntomas de próstata', 'síntomas de vejiga'],
    "ESTREÑIMIENTO": ['dolor abdominal agudo', 'flatulencia', 'náuseas', 'vómitos'],
    "FALLA CARDIACA DESCONPENSADA": ['disminución de la frecuencia cardíaca', 'aumento de la frecuencia cardíaca', 'dificultad para respirar', 'palpitaciones', 'fatiga'],
    "FALLA RESPIRATORIA": ['dificultad para respirar', 'respirando rápido'],
    "FIBROADENOMA DE LA MAMA": ['problemas mamarios posparto', 'dolor agudo en el pecho'],
    "FIEBRE TIFOIDEA": ['fiebre', 'problemas mamarios posparto', 'dolor agudo en el pecho', 'hinchazón del pie o del dedo del pie', 'dolor en el pie o en los dedos del pie', 'La piel de la pierna o el pie parece infectada.', 'dolor abdominal agudo', 'diarrea', 'debilidad'],
    "FLATULENCIA": ['flatulencia', 'dolor de cabeza', 'mareo', 'náuseas', 'reacción alérgica', 'picazón en la piel', 'erupción cutánea', 'congestión nasal', 'dolor muscular', 'síntomas emocionales'],
    "FRACTURA ABIERTA CON SANGRADO O DOLOR": ['sangrado del oído', 'sangrado en la boca', 'sangrado del ojo', 'sangrado intermenstrual', 'sangrado de lengua', 'sangrado rectal', 'sangrado o manchado durante el embarazo', 'sangrado o secreción del pezón', 'sangre en las heces'],
    "FRACTURA DE HUESOS DEL CRANEO Y DE LA CARA": ['síntomas de la cara', 'Los huesos duelen'],
    "FRACTURA DE HUESOS LARGOS": ['Los huesos duelen', 'períodos menstruales largos'],
    "FRACTURA DE LAS COSTILLAS DEL ESTERNON Y DE LA COLUMNA TORACICA DORSAL": ['dolor de costillas'],
    "FRACTURA DE MIEMBRO INFERIOR NIVEL NO ESPECIFICADO": ['dolor en la parte inferior del cuerpo'],
    "FRACTURA DE MIEMBRO SUPERIOR NIVEL NO ESPECIFICADO": ['dolor en la parte superior del abdomen'],
    "FRACTURAS": ['dolor en la mano o en los dedos', 'dolor en el pie o en los dedos del pie', 'dolor en la pierna', 'dolor en el brazo', 'sangre en la orina'],
    "FRACTURAS MULTIPLES": ['dolor en la mano o en los dedos', 'dolor en el pie o en los dedos del pie', 'dolor en la pierna', 'dolor en el brazo'],
    "HEMATEMESIS MASIVA": ['vomitar sangre', 'náuseas', 'vómitos'],
    "HEMATURIA": ['dolor en la mano o en los dedos', 'dolor en el pie o en los dedos del pie', 'dolor en la pierna', 'dolor en el brazo', 'sangrado intermenstrual', 'vomitar sangre', 'náuseas', 'vómitos', 'sangre en la orina', 'debilidad'],
    "HEMOPTISIS MODERADA": ['hemoptisis', 'pus en el esputo', 'tos', 'dificultad para respirar'],
    "HEMORRAGIA INTRACEREBRAL": ['hemorragia nasal', 'sangrado intermenstrual', 'debilidad', 'mareo', 'sangrado del ojo'],
    "HEMORRAGIA SUBARACNOIDEA": ['hemorragia nasal', 'sangrado intermenstrual', 'debilidad', 'mareo', 'sangrado del ojo'],
    "HEMORRAGIA SUBCONJUNTIVAL": ['hemorragia nasal', 'sangrado intermenstrual', 'debilidad', 'mareo', 'masa en la ingle', 'dolor abdominal agudo', 'sangrado del ojo'],
    "HEMORRAGIA SUBDURAL": ['hemorragia nasal', 'sangrado intermenstrual', 'debilidad', 'mareo', 'sangrado del ojo'],
    "HEMORRAGIA UTERINA DISFUNCIONAL": ['hemorragia nasal'],
    "HEPATITIS": ['vomitar sangre', 'náuseas', 'vómitos', 'sangre en la orina', 'pus en el esputo', 'tos', 'dificultad para respirar', 'hemorragia nasal', 'sangrado en la boca', 'dolor abdominal agudo'],
    "HERIDA DE CUELLO PARTE NO ESPECIFICADA": ['debilidad en el cuello', 'hinchazón del cuello', 'dolor de cuello', 'masa en el cuello', 'rigidez o tensión en el cuello', 'calambres o espasmos en el cuello', 'La piel de la cabeza o el cuello parece infectada.', 'sangrado intermenstrual', 'pus que drena del oído', 'audición disminuida'],
    "HERIDA DE LA CABEZA PARTE NO ESPECIFICADA": ['dolor de cabeza', 'La piel de la cabeza o el cuello parece infectada.', 'sangrado intermenstrual'],
    "HERIDA DE LA MUÑECA Y DE LA MANO PARTE NO ESPECIFICADA": ['Hinchazón de muñeca', 'debilidad en la muñeca', 'dolor de muñeca', 'bulto o masa en la muñeca', 'rigidez o tensión en la muñeca', 'Debilidad en la mano o en los dedos', 'dolor en la mano o en los dedos', 'Hinchazón de la mano o del dedo', 'masa en la ingle', 'dolor abdominal agudo'],
    "HERIDA DE LA PIERNA PARTE NO ESPECIFICADA": ['dolor en la pierna', 'bulto o masa en la pierna', 'La piel de la pierna o el pie parece infectada.', 'sangrado intermenstrual', 'masa en la ingle', 'dolor abdominal agudo', 'fiebre', 'enrojecimiento del pene', 'pus en el esputo', 'visión disminuida'],
    "HERIDA DE OTRA PARTE NO ESPECIFICADA": ['sangrado intermenstrual', 'sangre en la orina', 'debilidad', 'mareo', 'reacción alérgica', 'picazón en la piel', 'erupción cutánea', 'congestión nasal'],
    "HERIDA DE OTRAS PARTES Y DE LAS NO ESPECIFICADAS DEL HOMBRO Y DEL BRAZO": ['debilidad en el hombro', 'hinchazón del hombro', 'debilidad en el brazo', 'dolor en el brazo', 'dolor de hombro', 'hinchazón del brazo', 'rigidez en todas partes', 'dolor por todas partes'],
    "HERIDA DEL ANTEBRAZO PARTE NO ESPECIFICADA": ['sangrado intermenstrual'],
    "HERIDAS DE OTRAS PARTES Y DE LAS NO ESPECIFICADAS DEL ABDOMEN": ['abdomen hinchado', 'dolor en la parte baja del abdomen', 'dolor en la parte superior del abdomen', 'dolor por todas partes', 'rigidez en todas partes'],
    "HERIDAS POR VIOLENCIA": ['masa en la ingle', 'dolor abdominal agudo', 'visión disminuida', 'manchas o nubes en la visión', 'dolor muscular', 'síntomas emocionales'],
    "HERIDAS QUE AFECTAN MULTIPLES REGIONES DEL CUERPO": ['dolor en la parte inferior del cuerpo', 'Sensación de cuerpo extraño en el ojo'],
    "HERNIA INGUINAL": ['dolor agudo en el pecho', 'opresión en el pecho', 'palpitaciones', 'sangrado intermenstrual', 'debilidad', 'mareo', 'masa en la ingle', 'dolor abdominal agudo', 'visión disminuida', 'manchas o nubes en la visión'],
    "HIPERTENSION O HIPOTENSION LEVE": ['dolor de cabeza', 'mareo', 'hemorragia nasal', 'desmayo', 'debilidad'],
    "HIPERTENSION O HIPOTENSION SEVERA": ['dolor de cabeza', 'mareo', 'hemorragia nasal'],
    "HIPOACUSIA": ['debilidad', 'movimientos involuntarios anormales', 'dificultad para hablar', 'dolor suprapúbico', 'visión doble', 'audición disminuida', 'mareo', 'desmayo'],
    "ICTERICIA NEONATAL": ['ictericia', 'falta de crecimiento', 'náuseas', 'fatiga'],
    "IMPETIGO CUALQUIER SITIO ANATOMICO CUALQUIER ORGANISMO": ['sangrado intermenstrual', 'mareo', 'náuseas', 'erupción cutánea', 'enrojecimiento del pene', 'dolor de cabeza', 'hemorragia nasal'],
    "IMPOSIBILIDAD PARA DEGLUTIR SIN DISNEA": ['dificultad para tragar', 'dolor de garganta'],
    "INCONTINENCIA": ['incontinencia fecal', 'retención de orina', 'ictericia', 'náuseas', 'fatiga', 'dolor muscular', 'síntomas emocionales'],
    "INFARTO AGUDO": ['dolor agudo en el pecho', 'dolor abdominal agudo', 'opresión en el pecho', 'dificultad para respirar', 'palpitaciones', 'sangrado vaginal después de la menopausia', 'sangrado intermenstrual', 'dolor pélvico', 'dolor de rodilla', 'rigidez o tensión en la rodilla'],
    "INFECCION ASINTOMATICA POR VIH": ['dificultad para respirar', 'opresión en el pecho', 'tos', 'secreción peneana', 'fiebre', 'lesiones en la lengua'],
    "INFECCION DE HERIDA QUIRURGICA OBSTETRICA": ['fiebre', 'enrojecimiento del pene', 'pus en el esputo'],
    "INFECCION DE VIAS URINARIAS DURANTE EL EMBARAZO": ['problemas durante el embarazo', 'dolor durante el embarazo', 'sangrado o manchado durante el embarazo', 'embarazo reciente', 'micción excesiva durante la noche', 'dolor durante las relaciones sexuales', 'coágulos de sangre durante la menstruación', 'dolor suprapúbico', 'retención de orina', 'fiebre'],
    "INFECCION GONOCOCICA DEL TRACTO URINARIO": ['dolor suprapúbico', 'secreción peneana', 'fiebre', 'enrojecimiento del pene', 'pus en el esputo', 'síntomas depresivos o psicóticos', 'insomnio'],
    "INFECCION VIAS URINARIAS": ['dolor suprapúbico', 'retención de orina', 'fiebre', 'enrojecimiento del pene', 'pus en el esputo', 'fatiga'],
    "INSOMNIO": ['insomnio', 'voz ronca', 'dificultad para hablar', 'dolor vaginal', 'ansiedad y nerviosismo'],
    "INSUFICIENCIA CARDIACA CONGESTIVA": ['disminución de la frecuencia cardíaca', 'aumento de la frecuencia cardíaca', 'dificultad para respirar', 'palpitaciones'],
    "INSUFICIENCIA RESPIRATORIA AGUDA": ['dificultad para respirar', 'palpitaciones', 'respirando rápido'],
    "INTENTO DE SUICIDIO": ['síntomas emocionales', 'depresión'],
    "ISQUEMIAS": ['debilidad', 'dolor de cabeza', 'dificultad para hablar', 'dolor suprapúbico', 'fatiga', 'fiebre'],
    "LAGRIMEO": ['lagrimeo', 'dolor vaginal'],
    "LARINGOTRAQUEITIS": ['dolor abdominal agudo', 'náuseas', 'vómitos', 'fiebre', 'diarrea', 'tos', 'voz ronca', 'dificultad para respirar', 'dolor de garganta', 'dificultad para tragar'],
    "LESION PENETRANTE TORAX": ['lesión cutánea', 'lesión o erupción en el párpado'],
    "LESIONES EN MUCOSA ORAL": ['lesiones en la lengua'],
    "LESIONES POR VIOLENCIA": ['lesiones en la lengua', 'retención de orina', 'dolor muscular', 'síntomas emocionales'],
    "LEUCEMIA": ['debilidad', 'movimientos involuntarios anormales', 'dolor de cabeza', 'dificultad para hablar', 'fatiga', 'palidez', 'mareo', 'fiebre', 'retención de líquidos', 'dolor muscular'],
    "MAREO": ['mareo', 'dificultad para respirar', 'arritmia', 'dolor abdominal agudo'],
    "MASTALGIA": ['sangre en la orina', 'dolor agudo en el pecho', 'problemas mamarios posparto', 'fiebre', 'reacción alérgica', 'picazón en la piel', 'erupción cutánea', 'congestión nasal', 'pus que drena del oído', 'dolor de oído'],
    "MASTITIS POR LACTANCIA": ['dolor abdominal agudo', 'náuseas', 'vómitos', 'fiebre', 'problemas mamarios posparto', 'dolor agudo en el pecho'],
    "MENINGITIS": ['dolor de cabeza', 'fiebre', 'rigidez o tensión en el cuello', 'náuseas', 'vómitos', 'zumbido en el oído', 'audición disminuida', 'dolor abdominal agudo', 'dolor de garganta', 'dificultad para tragar'],
    "MENSTRUACIONES IRREGULARES": ['flujo menstrual escaso', 'flujo menstrual abundante', 'sangrado intermenstrual'],
    "MIOMATOSIS UTERINA": ['dolor pélvico', 'flujo menstrual abundante', 'dolor abdominal agudo'],
    "ODINOFAGIA, ADENOPATIAS Y FIEBRE": ['fiebre'],
    "OTALGIA OTORREA Y FIEBRE": ['fiebre', 'dolor abdominal agudo', 'diarrea', 'debilidad'],
    "OTRAS CATARATAS": ['dolor en el pie o en los dedos del pie', 'pus en el esputo', 'visión disminuida', 'manchas o nubes en la visión', 'dolor articular', 'hinchazón de las articulaciones'],
    "OTROS DOLORES ABDOMINALES Y LOS NO ESPECIFICADOS": ['dolor abdominal agudo', 'náuseas', 'vómitos'],
    "OTROS PROBLEMAS DE ALIMENTACION DEL RECIEN NACIDO": ['problema de alimentación infantil', 'problemas con el movimiento', 'problemas con el orgasmo', 'problemas posturales', 'problemas de temperamento', 'problemas de tabaquismo', 'problemas mamarios posparto', 'problemas durante el embarazo', 'dificultad para respirar', 'ictericia'],
    "OTROS TRASTORNOS DE ANSIEDAD": ['ansiedad y nerviosismo', 'uñas de aspecto irregular', 'palpitaciones', 'dificultad para respirar', 'síntomas depresivos o psicóticos', 'síntomas emocionales', 'insomnio'],
    "PALIDEZ CUTANEA Y FRIALDAD": ['palidez', 'erupción cutánea', 'lesión cutánea'],
    "PALPITACIONES CON PULSO IRREGULAR": ['palpitaciones', 'ombligo irregular', 'uñas de aspecto irregular', 'cuero cabelludo de aspecto irregular', 'flujo menstrual escaso', 'flujo menstrual abundante', 'sangrado intermenstrual'],
    "PALPITACIONES SIN COMPROMISO GENERAL": ['palpitaciones'],
    "PANCREATITIS AGUDA": ['dolor abdominal agudo', 'náuseas', 'fiebre', 'vómitos', 'dolor de garganta', 'dificultad para tragar', 'picazón en la piel', 'erupción cutánea', 'enrojecimiento del pene'],
    "PARESTESIAS ASOCIADAS A ANSIEDAD": ['ansiedad y nerviosismo'],
    "PARO RESPIRATORIO": ['dificultad para respirar', 'arritmia', 'respirando rápido', 'debilidad', 'movimientos involuntarios anormales', 'dificultad para hablar', 'depresión', 'insomnio', 'síntomas emocionales'],
    "PERDIDA SUBITA DE VISION": ['visión disminuida', 'pérdida de sensibilidad', 'visión doble', 'pérdida de peso reciente', 'pérdida del deseo sexual', 'manchas o nubes en la visión'],
    "PIE DIABETICO SOBREINFECTADO": ['hinchazón del pie o del dedo del pie', 'dolor en el pie o en los dedos del pie', 'Rigidez o tensión en el pie o en los dedos del pie.', 'bulto o masa en el pie o en el dedo del pie', 'debilidad en el pie o en los dedos', 'La piel de la pierna o el pie parece infectada.', 'calambres o espasmos en los pies o los dedos del pie.'],
    "PIELONEFRITIS": ['dolor abdominal agudo', 'náuseas', 'fiebre', 'vómitos', 'diarrea'],
    "PIROSIS": ['dificultad para respirar', 'respirando rápido', 'pus en el esputo', 'tos', 'hemorragia nasal', 'sangrado en la boca', 'debilidad', 'movimientos involuntarios anormales', 'dificultad para hablar', 'náuseas'],
    "POLINEUROPATIA, NO ESPECIFICADA": ['debilidad', 'movimientos involuntarios anormales', 'dolor de garganta', 'dificultad para tragar', 'fiebre', 'dolor suprapúbico'],
    "PROLAPSO GENITAL": ['flujo menstrual escaso', 'sangrado intermenstrual', 'dolor pélvico', 'retención de orina', 'problema de alimentación infantil', 'dificultad para respirar', 'síntomas depresivos o psicóticos', 'síntomas emocionales'],
    "PROLAPSO VAGINAL": ['dolor vaginal', 'picazón vaginal', 'flujo vaginal', 'enrojecimiento vaginal', 'sequedad vaginal', 'sangrado vaginal después de la menopausia', 'sangrado intermenstrual', 'dolor pélvico', 'retención de orina'],
    "PRURITO NO ESPECIFICADO": ['dolor abdominal agudo', 'picazón vaginal', 'flujo vaginal', 'picazón en la piel', 'erupción cutánea'],
    "PRURITO VAGINAL O FLUJO": ['flujo vaginal', 'dolor vaginal', 'picazón vaginal', 'enrojecimiento vaginal', 'sequedad vaginal', 'flujo menstrual escaso', 'flujo menstrual abundante', 'sangrado vaginal después de la menopausia'],
    "PSORIASIS NO ESPECIFICADA": ['dificultad para respirar', 'respirando rápido', 'hemorragia nasal', 'sangrado en la boca', 'debilidad', 'movimientos involuntarios anormales', 'náuseas', 'picazón en la piel', 'erupción cutánea'],
    "QUEMADURAS": ['quemaduras o picaduras en los ojos', 'sangre en la orina', 'debilidad', 'dolor de cabeza', 'dificultad para hablar'],
    "QUISTE  DE OVARIOS": ['dolor pélvico', 'dolor abdominal agudo', 'dolor de rodilla', 'rigidez o tensión en la rodilla'],
    "RECIEN NACIDO": ['dificultad para respirar', 'problema de alimentación infantil', 'ictericia'],
    "RETENCION DE PLACENTA": ['retención de orina', 'retención de líquidos', 'sangrado vaginal después de la menopausia', 'dolor abdominal agudo', 'dolor de cabeza', 'mareo', 'hemorragia nasal'],
    "RETENCION URINARIA": ['retención de orina', 'retención de líquidos', 'dolor suprapúbico', 'secreción peneana'],
    "RETENCION URINARIA AGUDA": ['retención de orina', 'retención de líquidos', 'dolor suprapúbico', 'sangrado vaginal después de la menopausia', 'dolor abdominal agudo'],
    "RETRASO MENSTRUAL CON SANGRADO": ['sangrado intermenstrual', 'sangrado de lengua', 'sangrado rectal', 'sangrado del ojo', 'sangrado del oído', 'sangrado en la boca', 'flujo menstrual escaso', 'flujo menstrual abundante', 'sangre en las heces', 'síntomas depresivos o psicóticos'],
    "RINORREA CONGESTION NASAL": ['congestión nasal', 'congestión sinusal', 'congestión en el pecho', 'hemorragia nasal', 'deformidad nasal'],
    "RINORREA, DOLOR FRONTAL, FIEBRE": ['fiebre', 'cefalea frontal'],
    "SANGRADO EN PACIENTE HEMOFILICO": ['sangrado del oído', 'sangrado del ojo', 'sangrado de lengua', 'sangrado en la boca', 'sangrado rectal', 'sangrado intermenstrual', 'sangrado o secreción del pezón', 'sangrado o manchado durante el embarazo', 'sangre en las heces'],
    "SANGRADO RECTAL SIN COMPROMISO": ['sangrado rectal', 'sangrado del oído', 'sangrado del ojo', 'sangrado en la boca', 'sangrado intermenstrual', 'sangrado de lengua', 'sangrado o secreción del pezón', 'sangre en las heces'],
    "SANGRADO VAGINAL": ['sangrado vaginal después de la menopausia', 'dolor vaginal', 'sequedad vaginal', 'picazón vaginal', 'flujo vaginal', 'enrojecimiento vaginal', 'sangrado del ojo', 'sangrado del oído', 'sangrado intermenstrual', 'dolor pélvico'],
    "SECRECION DE PUS URETRAL": ['secreción en las heces', 'secreción peneana', 'pus en la orina', 'pus en el esputo', 'sangrado o secreción del pezón', 'secreción blanca del ojo', 'pus que drena del oído', 'retención de orina', 'dolor suprapúbico'],
    "SECRECION TRANSVAGINAL FETIDA": ['secreción en las heces', 'secreción peneana', 'sangrado o secreción del pezón', 'secreción blanca del ojo', 'retención de orina', 'dolor suprapúbico', 'fiebre', 'enrojecimiento del pene', 'pus en el esputo'],
    "SEPSIS": ['pus en el esputo', 'tos', 'dificultad para respirar', 'hemorragia nasal', 'sangrado en la boca', 'náuseas', 'vómitos', 'fiebre'],
    "SHOCK": ['dificultad para respirar', 'debilidad'],
    "SHOCK  ANAFILACTICO": ['dificultad para respirar', 'debilidad'],
    "SINCOPE": ['dolor articular', 'hinchazón de las articulaciones', 'desmayo', 'mareo', 'debilidad'],
    "SINCOPE O LIPOTIMIA": ['desmayo', 'mareo', 'debilidad'],
    "SINDROME CONVULSIVO": ['síndrome parecido a la gripe', 'dolor muscular', 'convulsiones', 'movimientos involuntarios anormales', 'fiebre', 'fatiga'],
    "SINDROME DE INFECCION AGUDA": ['síndrome parecido a la gripe', 'fiebre', 'enrojecimiento del pene', 'pus en el esputo', 'fatiga'],
    "SINDROME EMETICO": ['síndrome parecido a la gripe', 'dolor pélvico', 'sangrado intermenstrual', 'hinchazón del pie o del dedo del pie', 'dolor en el pie o en los dedos del pie', 'La piel de la pierna o el pie parece infectada.', 'fiebre', 'fatiga'],
    "SINDROME FEBRIL": ['síndrome parecido a la gripe', 'fiebre', 'fatiga'],
    "SINDROME NEFRITICO": ['síndrome parecido a la gripe', 'fiebre', 'fatiga'],
    "TAQUICARDIA SUPRAVENTRICULAR": ['palpitaciones', 'arritmia', 'respirando rápido'],
    "TCE LEVE": ['dolor de cabeza', 'náuseas'],
    "TCE MODERADO": ['dolor de cabeza', 'náuseas'],
    "TINNITUS": ['dolor de cabeza', 'fiebre', 'rigidez o tensión en el cuello', 'náuseas', 'vómitos', 'zumbido en el oído', 'audición disminuida', 'flujo vaginal', 'picazón vaginal', 'dolor vaginal'],
    "TOS CON EXPECTORACION Y FIEBRE": ['fiebre', 'tos'],
    "TOS CRONICA": ['tos', 'pus en el esputo', 'dificultad para respirar'],
    "TOS SECA MALESTAR GENERAL FIEBRE": ['fiebre', 'tos'],
    "TOS SECA SIN COMPROMISO GENERAL": ['tos'],
    "TOXOPLASMOSIS": ['fiebre', 'dolor muscular', 'fatiga', 'dolor en la pierna', 'enrojecimiento del pene'],
    "TRASNTORNO SICOTICO AGUDO": ['dolor agudo en el pecho', 'dolor abdominal agudo', 'síntomas depresivos o psicóticos', 'insomnio'],
    "TRASTORNO AFECTIVO BIPOLAR": ['síntomas depresivos o psicóticos', 'síntomas emocionales', 'insomnio'],
    "TRASTORNO DE LA UÑA NO ESPECIFICADO": ['mareo', 'uñas de aspecto irregular', 'síntomas depresivos o psicóticos', 'síntomas emocionales', 'insomnio'],
    "TRASTORNO MENTAL": ['dolor abdominal agudo', 'flujo menstrual escaso', 'sangrado intermenstrual', 'uñas de aspecto irregular', 'síntomas depresivos o psicóticos', 'síntomas emocionales', 'insomnio'],
    "TRASTORNO MENTAL ORGANICO O SINTOMATICO NO ESPECIFICADO": ['síntomas depresivos o psicóticos', 'síntomas emocionales'],
    "TRAUMA CERRADO": ['dolor muscular', 'dolor de espalda', 'síntomas del ojo', 'sangrado del ojo', 'dolor en el ojo'],
    "TRAUMA CERRADO DE MANO Y PIE": ['dolor en el pie o en los dedos del pie', 'hinchazón del pie o del dedo del pie', 'bulto o masa en el pie o en el dedo del pie', 'Rigidez o tensión en el pie o en los dedos del pie.', 'rigidez o tensión en la mano o los dedos', 'dolor en la mano o en los dedos', 'Debilidad en la mano o en los dedos', 'Hinchazón de la mano o del dedo'],
    "TRAUMA CON DOLOR TOLERABLE SIN COMPROMISO VASCULAR": ['dolor muscular', 'dolor de espalda', 'dolor de tobillo', 'dolor de garganta', 'dolor de lengua', 'dolor de rodilla', 'dolor de mandíbula', 'dolor de piel'],
    "TRAUMA EN CADERA CON DOLOR": ['dolor de cadera', 'debilidad de cadera', 'hinchazón de cadera', 'bulto o masa en la cadera', 'rigidez o tensión en la cadera', 'dolor de codo', 'dolor de garganta', 'dolor en el brazo', 'dolor de cabeza', 'náuseas'],
    "TRAUMA FACIAL CON OBSTRUCCION DE LA VIA AEREA": ['dolor facial'],
    "TRAUMA NASAL SIN DISNEA": ['deformidad nasal', 'congestión nasal', 'hemorragia nasal'],
    "TRAUMA OCULAR NO AGUDO": ['fatiga ocular', 'desviación ocular', 'dolor agudo en el pecho', 'dolor abdominal agudo', 'lagrimeo', 'síntomas del ojo', 'sangrado del ojo', 'dolor en el ojo'],
    "TRAUMA OCULAR QUIMICO O FISICO": ['desviación ocular', 'fatiga ocular', 'síntomas del ojo', 'sangrado del ojo', 'dolor en el ojo'],
    "TRAUMA PENETRANTE": ['dolor muscular', 'dolor de espalda'],
    "TRAUMATISMO CRANEOENCEFALICO": ['dolor de cabeza', 'náuseas'],
    "TRAUMATISMO DEL OJO Y DE LA ORBITA": ['síntomas del ojo', 'sangrado del ojo', 'dolor en el ojo', 'picazón en el ojo', 'ojo hinchado', 'ojo nublado', 'secreción blanca del ojo', 'El ojo se mueve de forma anormal.', 'dolor de cabeza', 'náuseas'],
    "TRAUMATISMOS SUPERFICIALES MULTIPLES DEL ANTEBRAZO": ['dolor de cabeza', 'náuseas'],
    "TUBERCULOSIS": ['pus en el esputo', 'enrojecimiento del pene', 'dolor de piel', 'tos', 'fiebre', 'dolor en la pierna'],
    "ULCERA CRONICA DE LA PIEL NO CLASIFICADA EN OTRA PARTE": ['úlcera bucal', 'hinchazón de la piel', 'irritación de la piel', 'picazón en la piel', 'dolor de piel', 'crecimiento de la piel', 'lunares en la piel', 'piel grasa'],
    "ULCERA DE MIEMBRO INFERIOR NO CLASIFICADA EN OTRA PARTE": ['úlcera bucal', 'dolor en la parte inferior del cuerpo'],
    "ULCERA PEPTICA": ['úlcera bucal', 'dolor abdominal agudo', 'náuseas'],
    "URTICARIA ALERGICA": ['reacción alérgica', 'dificultad para respirar', 'palpitaciones', 'arritmia', 'respirando rápido', 'mareo', 'dolor abdominal agudo', 'náuseas', 'retención de orina', 'dolor suprapúbico'],
    "URTICARIA NO ESPECIFICADA": ['palpitaciones', 'arritmia', 'respirando rápido', 'mareo', 'dificultad para respirar', 'reacción alérgica', 'picazón en la piel', 'erupción cutánea', 'ictericia', 'náuseas'],
    "URTICARIAS": ['palpitaciones', 'arritmia', 'respirando rápido', 'mareo', 'dificultad para respirar', 'opresión en el pecho', 'tos', 'reacción alérgica', 'picazón en la piel', 'erupción cutánea'],
    "UÑA ENCARNADA": ['dolor en el pie o en los dedos del pie', 'pus en el esputo', 'visión disminuida', 'manchas o nubes en la visión'],
    "VAGINISMO": ['flujo vaginal', 'picazón vaginal', 'dolor vaginal', 'insomnio', 'ansiedad y nerviosismo', 'dolor abdominal agudo', 'dolor de espalda'],
    "VAGINITIS AGUDA": ['dolor de garganta', 'fiebre', 'dificultad para tragar', 'flujo vaginal', 'picazón vaginal', 'dolor vaginal', 'sangrado vaginal después de la menopausia', 'sangrado intermenstrual', 'dolor pélvico'],
    "VERRUGAS ANOGENITALES": ['verrugas', 'lesión cutánea'],
    "VERTIGO CON EMESIS": ['mareo', 'náuseas', 'vómitos'],
    "VERTIGO SIN EMESIS": ['mareo', 'náuseas', 'vómitos'],
    "VIOLENCIA DE GENERO": ['retención de orina', 'dolor muscular', 'síntomas emocionales'],
    "VOMITO SIN SANGRE": ['vomitar sangre', 'sangre en la orina', 'sangre en las heces', 'coágulos de sangre durante la menstruación', 'sangrado vaginal después de la menopausia', 'sangrado intermenstrual', 'dolor pélvico'],
}

# ============================================================
# PARÁMETROS DE MODELOS
# ============================================================
# RANDOM FOREST
RF_PARAMS = {
    "n_estimators": 200,
    "max_depth": 20,
    "min_samples_split": 5,
    "min_samples_leaf": 2,
    "random_state": RANDOM_STATE,
    "n_jobs": -1,
}

# XGBOOST
XGB_PARAMS = {
    "n_estimators": 200,
    "max_depth": 10,
    "learning_rate": 0.1,
    "random_state": RANDOM_STATE,
    "n_jobs": -1,
    "eval_metric": "mlogloss",
}

# REGRESIÓN LOGÍSTICA
LR_PARAMS = {
    "max_iter": 300,
    "C": 1.0,
    "solver": "saga",      # saga es mucho más rápido para datasets grandes (>100k)
    "random_state": RANDOM_STATE,
    "n_jobs": -1,
}

